name: pinklotus
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  google_fonts: ^6.1.0
  syncfusion_flutter_charts: ^29.2.9
  pin_code_fields: ^8.0.1
  dio: ^5.8.0+1
  fluttertoast: ^8.2.12
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  http: ^1.4.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  mime_type: ^1.0.1
  mime:
  file_selector: ^1.0.3
  url_launcher: ^6.3.2
  flutter_markdown: ^0.7.7+1
  multi_select_flutter: ^4.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  fl_chart:  ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/app_logo_login.svg
    - assets/drawer/
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
